# Generated by Django 4.1.7 on 2023-03-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_simpleuser_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleuser',
            name='url',
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
