# Generated by Django 4.1.7 on 2023-03-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_simpleuser_url_simpleuser_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='utm',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
